kind: ConfigMap
apiVersion: v1
metadata:
  name: pit-claim-ui-config-#{ENV}#
  namespace: '#{NAMESPACE}#'
  labels:
    app: pit-claim-ui-#{ENV}#
    project: brmb-pit-claim-#{ENV}#
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-04-15T22:11:17Z'
      fieldsType: FieldsV1
immutable: false
data:
  TOMCAT_PORT: '#{TOMCAT_PORT}#'
  TOMCAT_MAX_THREADS: '#{TOMCAT_MAX_THREADS}#'
  CONNECTION_TIMEOUT: '#{CONNECTION_TIMEOUT}#'
  BASE_URL: '#{BASE_URL}#'
  CIRRAS_CLAIMS_REST_URI: '#{CIRRAS_CLAIMS_REST_URI}#'
  WEBADE_OAUTH2_AUTHORIZE_URL: '#{WEBADE_OAUTH2_AUTHORIZE_URL}#'
  WEBADE_OAUTH2_ENABLE_CHECKTOKEN: '#{WEBADE_OAUTH2_ENABLE_CHECKTOKEN}#'
  LOCAL_CHECKTOKEN_ENDPOINT: '#{LOCAL_CHECKTOKEN_ENDPOINT}#'
  WEBADE_CHECK_TOKEN_URL: '#{WEBADE_CHECK_CLIENT_TOKEN_URL}#'
  WEBADE_OAUTH2_SITEMINDER_URL: '#{WEBADE_OAUTH2_SITEMINDER_URL}#'
  WEBADE_GET_TOKEN_URL: '#{WEBADE_GET_CLIENT_TOKEN_URL}#'
  WEBADE_OAUTH2_SCOPES: '#{WEBADE_OAUTH2_SCOPES}#'
  ACTIVE_PORT: '#{ACTIVE_PORT}#'
  WEB_PATH: '#{WEB_PATH}#'
  LOG_LEVEL: '#{LOG_LEVEL}#'
